### ISSUE TITLE
Documentation for MSA tools

### ISSUE THREAD

**Issue by hansli112** [carlosholivan/musicaiz#10]
I've read the paper "Symbolic Music Structure Analysis with Graph Representations and Changepoint Detection Methods". But it seems that there is no documentation for the 3 algorithms mentioned in the paper nor the inference codes.

**Comment by carlosholivan** [comment]
Hi,
Since the code was not clean enough to be added to this package, we pushed it to other repository: https://github.com/carlosholivan/symbolic-music-structure-analysis
I am still working on other algorithms for MSA, and I plan to add the best-performing ones to this package once the code is clean enough.
